name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [Win32, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild (VS 2022)
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.0'

      - name: Build Debug ${{ matrix.platform }}
        shell: pwsh
        run: |
          msbuild .\\pelauncher.sln /m /p:Configuration=Debug /p:Platform=${{ matrix.platform }} /p:PreferredToolArchitecture=x64 /restore

      - name: Upload artifact (Debug ${{ matrix.platform }})
        uses: actions/upload-artifact@v4
        with:
          name: Debug-${{ matrix.platform }}
          path: build/Debug/${{ matrix.platform }}/

